### ISSUE TITLE
Latest release does not work with Websphere Liberty(Open Liberty) in a Docker container

### ISSUE THREAD

**Issue by tomaszcaibm** [stephen-kruger/bluebox#21]
Compared to 4.5.3 release, there are several issues with latest release:

1. The configuration override is not picked up.
2. There are warnings about logging not having providers available during startup.
3. When email is delivered to the server, there is a NullPointerException printed on console:
```
[err] java.lang.NullPointerException
[err]   at com.bluebox.smtp.storage.h2.H2Impl.setProperty(H2Impl.java:629)
[err]   at com.bluebox.smtp.storage.h2.H2Impl.logError(H2Impl.java:691)
[err]   at com.bluebox.smtp.Inbox.errorLog(Inbox.java:819)
[err]   at com.bluebox.smtp.Inbox.deliver(Inbox.java:709)
[err]   at org.subethamail.smtp.helper.SimpleMessageListenerAdapter$Handler.data(SimpleMessageListenerAdapter.java:158)
[err]   at org.subethamail.smtp.command.DataCommand.execute(DataCommand.java:64)
[err]   at org.subethamail.smtp.server.RequireTLSCommandWrapper.execute(RequireTLSCommandWrapper.java:30)
[err]   at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:99)
[err]   at org.subethamail.smtp.server.Session.runCommandLoop(Session.java:244)
[err]   at org.subethamail.smtp.server.Session.run(Session.java:145)
[err]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err]   at java.lang.Thread.run(Thread.java:823)
```

Following Docker file was used to build the images to run:
```Dockerfile
FROM open-liberty:kernel-slim

COPY --chown=1001:0  server.xml /config/

RUN features.sh

COPY --chown=1001:0  bluebox.war /config/apps/bluebox.war

ARG VERBOSE=false

RUN configure.sh

USER root
RUN mkdir -p /home/default && chown -R 1001:0 /home/default
USER 1001

COPY --chown=1001:0  bluebox/bluebox.properties /home/default/bluebox.properties
```

The above works fine with release 4.5.3.

**Comment by stephen-kruger** [comment]
Could you paste your server.xml?

**Comment by stephen-kruger** [comment]
Can you try the latest 4.7.0 release and see if it works?
Please follow the instructions in the README, and use the right server.xml etc
